#!/usr/bin/env bash

set-option -sa terminal-overrides ",xterm*:Tc"

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g mouse on
set -gq allow-passthrough all

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Plugins

source-file "${XDG_CONFIG_HOME}/tmux/plugins.conf"

set -g @tokyo-night-tmux_theme storm
set -g @tokyo-night-tmux_transparent 1

set -g @tokyo-night-tmux_show_git 0
set -g @tokyo-night-tmux_show_wbg 0
set -g @tokyo-night-tmux_show_netspeed 0
set -g @tokyo-night-tmux_show_battery_widget 0
set -g @tokyo-night-tmux_show_music 0
set -g @tokyo-night-tmux_show_path 0
set -g @tokyo-night-tmux_show_hostname 1
