dictionaries = [
    "en_us",
    "ru",
]
words = [
    "clickhouse",
    "hft",
    "llm",
    "nginx",
    "nixpkgs",
    "pkgs",
    "profiler",
    "proj",
    "rdkafka",
    "solana",
    "sqlx",
    "ООП",
    "блокчейн",
    "нейронку",
    "офер",
    "ребрендинг",
    "самозанятости",
]
