services:
  'git.tt-int.net': 'gitlab:git.tt-int.net'

# What to do when opening Lazygit outside of a git repo.
# - 'prompt': (default) ask whether to initialize a new repo or open in the most recent repo
# - 'create': initialize a new repo
# - 'skip': open most recent repo
# - 'quit': exit Lazygit
notARepository: quit

# If true, periodically fetch from remote
# AND PROMT FOR SSH PASSWORD
autoFetch: true

promptToReturnFromSubprocess: false

# both diff alternatives are lame af
git:
  paging:
    # byte limit x100 the default
    # graph limit x100 the default
    # externalDiffCommand: difft --color=always --syntax-highlight on --display inline --byte-limit 100000000 --graph-limit 300000000

    # colorArg: always
    # pager: delta --dark --paging=never

os:
  edit: |
    if [[ ${EDITOR:0:4} == "nvim" ]]; then
      nvim --server "$NVIM_PIPE" --remote {{filename}}
      if [ ! -z $NVIM_PIPE ]; then
          kill -TERM $(ps -o ppid= -p $$)
      fi
    else
      $EDITOR
    fi
  editAtLine: |
    if [[ ${EDITOR:0:4} == "nvim" ]]; then
      nvim --server "$NVIM_PIPE" --remote {{filename}}
      nvim --server "$NVIM_PIPE" --remote-send "<Esc>:{{line}}<CR>"
      if [ ! -z $NVIM_PIPE ]; then
          kill -TERM $(ps -o ppid= -p $$)
      fi
    else
      $EDITOR
    fi
