windowrule = match:title ^(nnn-file-manager)$, float on
# windowrule = match:title ^(nnn-file-manager)$, dim_around on
windowrule = match:title ^(nnn-file-manager-preview)$, float on

# windowrule = match:title ^(nnn-file-manager)$, size (monitor_w*0.3) (monitor_h*0.6)
# windowrule = match:title ^(nnn-file-manager)$, move (monitor_w*0.08) (monitor_h*0.2)
# windowrule = match:title ^(nnn-file-manager-preview)$, size (monitor_w*0.5) (monitor_h*0.8)
# windowrule = match:title ^(nnn-file-manager-preview)$, move (monitor_w*0.4) (monitor_h*0.1)

# HACK: until I figure out Kitty min window size
windowrule = match:title ^(nnn-file-manager)$, size (monitor_w*0.3) (monitor_h*0.6)
windowrule = match:title ^(nnn-file-manager)$, move (monitor_w*0.1) (monitor_h*0.2)
windowrule = match:title ^(nnn-file-manager-preview)$, size (monitor_w*0.5) (monitor_h*0.8)
windowrule = match:title ^(nnn-file-manager-preview)$, move (monitor_w*0.5) (monitor_h*0.1)

windowrule = match:title ^(nnn-file-manager)$, no_dim on
windowrule = match:title ^(nnn-file-manager-preview)$, no_dim on

windowrule = match:title ^(nnn-file-manager-preview)$, no_initial_focus on
windowrule = match:title ^(nnn-file-manager-preview)$, no_anim on

bindd = $mainMod, E, launch file Explorer, exec, app2unit -- bb ~/.local/bin/file-manager
