version: 2
root-markers:
  - .git/
lint-debounce: 1s

tools:
  markdown-markdownlint: &markdown-markdownlint
    lint-command: "markdownlint -s"
    lint-stdin: true
    lint-formats:
      - "%f:%l %m"
      - "%f:%l:%c %m"
      - "%f: %l: %m"

languages:
  markdown:
    - <<: *markdown-markdownlint
