experimental-features = nix-command flakes

# Require trusted user, see
# https://discourse.nixos.org/t/trusted-user-errors-for-every-nix-command-on-arch/14295

# keep-outputs = true
# keep-derivations = true
# auto-optimise-store = true

download-attempts = 50
