# showmethekey
windowrule = match:initial_title ^(Floating Window - Show Me The Key)$, float on
windowrule = match:initial_title ^(Floating Window - Show Me The Key)$, pin on
windowrule = match:initial_title ^(Floating Window - Show Me The Key)$, no_dim on
windowrule = match:initial_title ^(Floating Window - Show Me The Key)$, border_size 0
windowrule = match:initial_title ^(Floating Window - Show Me The Key)$, no_shadow on
windowrule = match:initial_title ^(Floating Window - Show Me The Key)$, no_focus on
windowrule = match:initial_title ^(Floating Window - Show Me The Key)$, no_blur on
windowrule = match:initial_title ^(Floating Window - Show Me The Key)$, size (monitor_w*0.2) (monitor_h*0.06)
windowrule = match:initial_title ^(Floating Window - Show Me The Key)$, move ((monitor_w*0.5)-(monitor_w*0.2)*0.5) (monitor_h*0.9)
