# Set to true to use lowercase keywords instead of uppercase.
lowercaseKeywords: false
connections:
  - alias: pg
    driver: postgresql
    dataSourceName: host=127.0.0.1 port=5432 user=postgres password=nopassword sslmode=disable
