services:
  'git.tt-int.net': 'gitlab:git.tt-int.net'

# What to do when opening Lazygit outside of a git repo.
# - 'prompt': (default) ask whether to initialize a new repo or open in the most recent repo
# - 'create': initialize a new repo
# - 'skip': open most recent repo
# - 'quit': exit Lazygit
notARepository: quit

promptToReturnFromSubprocess: false

git:
  # If true, periodically fetch from remote
  # AND PROMT FOR SSH PASSWORD
  autoFetch: false

  pagers:
    - pager: delta --syntax-theme tokyonight-storm --dark --paging=never

os:
  edit: |
    if [[ $VISUAL == nvim* ]] && { [[ -v NVIM_PIPE ]] || [[ -v NVIM ]]; }; then
      nvim --server ${NVIM:-${NVIM_PIPE}} --remote-send '<cmd>lua require("git").lazygit_edit_file({{filename}})<CR>'

      if [[ -v NVIM_PIPE ]] && [[ ! -v NVIM ]]; then
        kill -TERM $(ps -o ppid= -p $$)
      fi
    else
      $VISUAL -- {{filename}}
    fi 
  editAtLine: |
    if [[ $VISUAL == nvim* ]] && { [[ -v NVIM_PIPE ]] || [[ -v NVIM ]]; }; then
      nvim --server ${NVIM:-${NVIM_PIPE}} --remote-send '<cmd>lua require("git").lazygit_edit_file({{filename}}, {{line}})<CR>'

      if [[ -v NVIM_PIPE ]] && [[ ! -v NVIM ]]; then
        kill -TERM $(ps -o ppid= -p $$)
      fi
    else
      $VISUAL +{{line}} -- {{filename}}
    fi 
