#! /bin/sh

# TODO: clone db using sqlite3 tools othewise it will be currepted
# https://stackoverflow.com/a/5275022
dest=$HOME/data/backups/shell-history/
mkdir -p $dest
cp ~/.local/share/atuin/history.db $dest
mv $dest/history.db $dest/atuin_$(date +%Y-%m-%d_%H-%M-%S).db

restic \
    --repo sftp:jupiter:/mnt/backup-storage \
    --password-command "pass jupiter-backup" \
    --verbose \
    backup ~/data
