#! /bin/sh

set -e

deep_clean_docker() {(
    docker container prune -f
    docker volume prune -f
    docker image prune -af
)}

deep_clean_cargo() {(
    find . -type f -name 'Cargo.toml' | parallel cargo clean --manifest-path {}
    cargo cache -a
)}

# deep_clean_nix() {(
#     nix-collect-garbage -d
#     nix profile wipe-history
#     nix store gc
#     nix store optimise
# )}

sudo_deep_clean_nix() {(
    sudo nix-collect-garbage -d
    nix profile wipe-history
    nix store gc
    nix store optimise
)}


deep_clean_docker &
deep_clean_cargo &
sudo_deep_clean_nix

set +e
