#! /bin/sh

deep_clean_docker() {(
    docker container prune -f
    docker volume prune -f
    docker image prune -af
)}

deep_clean_cargo() {(
    rm -rf \
        ${CARGO_HOME}/shared-target \
        ${CARGO_HOME}/git/db \
        ${CARGO_HOME}/git/checkouts \
        ${CARGO_HOME}/registry/index \
        ${CARGO_HOME}/registry/cache \
        ${CARGO_HOME}/registry/src
)}

# deep_clean_nix() {(
#     nix-collect-garbage -d
#     nix profile wipe-history
#     nix store gc
#     nix store optimise
# )}

sudo_deep_clean_nix() {(
    find ~/code -type d -name '.direnv' -print -execdir rm -fr .direnv \;
    find ~/tradetech -type d -name '.direnv' -print -execdir rm -fr .direnv \;
    find ~/tradetech-2021 -type d -name '.direnv' -print -execdir rm -fr .direnv \;

    home-manager expire-generations 0
    sudo nix-collect-garbage -d
    nix profile wipe-history
    nix store gc
    nix store optimise
)}

# a handy way to enter sudo password
sudo echo "Cleaning everything !"

deep_clean_docker &
deep_clean_cargo &
sudo_deep_clean_nix

# extra mesures

# for zsh
# setopt localoptions rmstarsilent
# trash-empty -f
# yes | rm -fr ~/.cache
# yes | rm -fr ~/playground/*
