#! /bin/sh

#     -o "%(album_artist&{} - |)s%(album|singletones)s/%(creator&{} - |)#s%(track,title)#s.%(ext)s" \

yt-dlp \
    -P $HOME/data/knowledge-base/media/music/import-source/ \
    -o "%(creator).200B%(creator.201&...|)s%(creator& - |)#s%(track,title)#s.%(ext)s" \
    --download-archive $HOME/data/knowledge-base/media/music/dlp-index.txt \
    -f bestaudio \
    --extract-audio \
    --embed-thumbnail \
    --embed-metadata \
    --cookies-from-browser firefox \
    "https://music.youtube.com/playlist?list=PL3IFklmt6R9CVSzOPwWqovvz2gHEFaIEZ"

yt-dlp \
    -P $HOME/data/knowledge-base/media/music/import-source/ \
    -o "%(creator).200B%(creator.201&...|)s%(creator& - |)#s%(track,title)#s.%(ext)s" \
    --download-archive $HOME/data/knowledge-base/media/music/dlp-index.txt \
    -f bestaudio \
    --extract-audio \
    --embed-thumbnail \
    --embed-metadata \
    --cookies-from-browser firefox \
    "https://music.youtube.com/playlist?list=LM"

# --extractor-args "youtubetab:skip=authcheck" \

# yt-dlp \
#     -P $HOME/data/knowledge-base/media/music/import-source/ \
#     -o "%(creator&{} - |)#s%(track,title)#s.%(ext)s" \
#     -f bestaudio \
#     --extract-audio \
#     --audio-format flac \
#     --embed-metadata \
#     "https://www.youtube.com/playlist?list=PL3IFklmt6R9DHmsaCHYD4REmLYIII4rn2"
