#! /bin/sh

set -e

# parrent_path=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")
# cd $parrent_path

[ -z "$1" ] && echo "path to migrations must be set, aborting" && exit

migrations=$1
port=${2:-8123}
name_prefix=${3:-test}

up_only=$(mktemp -d /tmp/up-only-XXXXXX)
ls -d $migrations/* | grep '\.up.sql' | xargs cp -t $up_only

docker_name=${name_prefix}-ch-db
docker run --rm -dit -p "${port}:8123" -v $up_only:/docker-entrypoint-initdb.d:ro --name $docker_name clickhouse/clickhouse-server:$(cat $migrations/version)
# docker run --rm -dit -p "${port}:8123" -v $up_only:/docker-entrypoint-initdb.d:ro --name $docker_name yandex/clickhouse-server:$(cat $migrations/version)

# docker run --rm -it -p "${port}:8123" -v $up_only:/docker-entrypoint-initdb.d:ro --name $docker_name clickhouse/clickhouse-server:$(cat $migrations/version)
# docker run --rm -it -p "${port}:8123" -v $up_only:/docker-entrypoint-initdb.d:ro --name $docker_name yandex/clickhouse-server:$(cat $migrations/version)

set +e
