# vim:fileencoding=utf-8:foldmethod=marker

# Reset default keymaps
clear_all_shortcuts yes

# --------------------------------------------------------------------------------
# Font
# --------------------------------------------------------------------------------

# font_family family="Fira Code"
font_family family="JetBrains Mono"
font_size 9

# Nerd Fonts
# https://www.reddit.com/r/KittyTerminal/comments/r5hssh/comment/jnao28q
# https://github.com/Sharparam/dotfiles/blob/main/kitty/.config/kitty/font-nerd-symbols.conf

# --------------------------------------------------------------------------------
# General
# --------------------------------------------------------------------------------

modify_font cell_height 90%
modify_font baseline 1
modify_font underline_position 2

text_composition_strategy legacy
disable_ligatures cursor

cursor_shape beam
cursor_blink_interval 0.5
cursor_trail 1

scrollback_lines 100000

# kitty-scrollback.nvim integration
action_alias kitty_scrollback_nvim kitten '$XDG_DATA_HOME/nvim/site/pack/hm/start/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py'
map ctrl+shift+h kitty_scrollback_nvim

url_style straight

enable_audio_bell no
update_check_interval 0
# TODO: shell integration
notify_on_cmd_finish unfocused
confirm_os_window_close 0
allow_remote_control yes
listen_on unix:/tmp/kitty-socket

# --------------------------------------------------------------------------------
# Colorscheme
# --------------------------------------------------------------------------------

## name: Tokyo Night Storm
## license: MIT
## author: Folke Lemaitre
## upstream: https://github.com/folke/tokyonight.nvim/raw/main/extras/kitty/tokyonight_storm.conf

background #24283b
foreground #c0caf5
selection_background #2e3c64
selection_foreground #c0caf5
url_color #73daca
cursor #c0caf5
cursor_text_color #24283b

# Tabs
active_tab_background #7aa2f7
active_tab_foreground #1f2335
inactive_tab_background #292e42
inactive_tab_foreground #545c7e
#tab_bar_background #1d202f

# Windows
active_border_color #7aa2f7
inactive_border_color #292e42

# normal
color0 #1d202f
color1 #f7768e
color2 #9ece6a
color3 #e0af68
color4 #7aa2f7
color5 #bb9af7
color6 #7dcfff
color7 #a9b1d6

# bright
color8  #414868
color9  #ff899d
color10 #9fe044
color11 #faba4a
color12 #8db0ff
color13 #c7a9ff
color14 #a4daff
color15 #c0caf5

# extended colors
color16 #ff9e64
color17 #db4b4b

# --------------------------------------------------------------------------------
# Keymaps
# --------------------------------------------------------------------------------

kitty_mod alt

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

map ctrl+k scroll_to_prompt -1
map ctrl+j scroll_to_prompt 1
map ctrl+up scroll_line_up
map ctrl+down scroll_line_down
map page_up scroll_page_up
map page_down scroll_page_down

map ctrl+plus change_font_size all +2.0
map ctrl+minus change_font_size all -2.0
map ctrl+equal change_font_size all 0

map ctrl+l open_url_with_hints
map ctrl+shift+l kitten hints --type path --program wl-copy

map ctrl+p kitten hints --type path --program -
map ctrl+o kitten hints --type path

map kitty_mod+f3 command_palette
map kitty_mod+f5 load_config_file
