[unstable]
# https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#profile-rustflags-option
profile-rustflags = true

# Example
[registries.internal]
index = "ssh://git@git.private-service.net/path/to/index.git"
