[pyprland]
plugins = ["scratchpads"]

[scratchpads.messenger]
command = "cinny"
animation = "fromTop"
size = "70% 80%"

[scratchpads.telegram]
command = "telegram-desktop"
animation = "fromTop"
size = "70% 80%"

[scratchpads.terminal]
command = "foot --title terminal-popup"
class = "terminal-popup"
animation = "fromTop"
size = "70% 80%"

[scratchpads.music-player]
command = "foot --title music-player ncmpcpp"
animation = "fromTop"
size = "70% 80%"
