#! /usr/bin/env sh

export NNN_OPTS="aAG"

if command -v cpg >/dev/null 2>&1 && command -v mvg >/dev/null 2>&1; then
    export NNN_OPTS="${NNN_OPTS}r"
fi

export NNN_FIFO=/tmp/nnn.fifo

# flash firmware to keyboard using only mouse
export NNN_MCLICK='p'

export NNN_TERMINAL="${TERMINAL}"

export NNN_PLUG=\
'v:preview-tui;'\
'd:dragdrop;'\
'j:fzcd;'\
'r:gitroot;'\
'w:wallpaper;'\
's:xdgdefault;'\
'o:fzopen;'\
'h:!cppath "$nnn"*;'\
'y:-!wayland-copy-file "$nnn"*;'\
'p:!wayland-paste-file*'

if command -v trash-cli >/dev/null 2>&1; then
    export NNN_TRASH=1
fi

export NNN_BMS="\
c:$HOME/.config;\
l:$HOME/.local;\
t:$HOME/.local/share/Trash;\
P:$HOME/.local/share/PrismLauncher/instances;\
M:$HOME/mercury;\
p:$HOME/playground;\
m:$HOME/data/knowledge-base/media;\
z:$HOME/data/knowledge-base/media/music;\
i:$HOME/data/knowledge-base/media/images;\
w:$HOME/data/knowledge-base/media/wallpapers;\
e:/run/media/$USER;\
s:/run/current-system/sw;\
u:/etc/profiles/per-user/$USER"
